name: Build Docker images

on:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into DockerHub registry
        if: ${{ github.event_name != 'pull_request' && github.repository == 'wallernetwork/docker-genisoimage' }}

        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log into registry GitHub registry
        if: ${{ github.event_name != 'pull_request' && github.repository == 'wallernetwork/docker-genisoimage' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate build timestamp
        id: timestamp
        run: echo "::set-output name=date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

      - name: Shorten commit hash
        id: commit
        run: echo "::set-output name=sha::${GITHUB_SHA::7}"

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: > 
            linux/386, 
            linux/amd64, 
            linux/arm/v6,
            linux/arm/v7, 
            linux/arm64, 
            linux/mips64le, 
            linux/ppc64le, 
            linux/s390x
          push: ${{ github.event_name != 'pull_request' && github.repository == 'wallernetwork/docker-genisoimage' }}
          build-args: |
            BUILD_DATE=${{ steps.timestamp.outputs.date }}
            REVISION=${{ steps.commit.outputs.sha }}
          tags: |
            wallernetwork/genisoimage:latest
            ghcr.io/wallernetwork/genisoimage:latest
